package principal

import (
	"context"
	"strings"
	"testing"

	keeldata "github.com/nauticana/keel/data"
	keelmodel "github.com/nauticana/keel/model"
	keelport "github.com/nauticana/keel/port"

	"github.com/nauticana/scout/domain"
)

type authQueryFake struct {
	registered map[string]string
	asked      string
	args       []any
	rows       [][]any
}

func (q *authQueryFake) Query(_ context.Context, name string, args ...any) (*keelmodel.QueryResult, error) {
	q.asked, q.args = name, append([]any(nil), args...)
	return &keelmodel.QueryResult{Rows: q.rows}, nil
}

func (*authQueryFake) GenID() int64                   { return 1 }
func (*authQueryFake) Commit(context.Context) error   { return nil }
func (*authQueryFake) Rollback(context.Context) error { return nil }

type authDBFake struct {
	keelport.DatabaseRepository
	query *authQueryFake
}

func (db authDBFake) GetQueryService(_ context.Context, queries map[string]string) keelport.QueryService {
	db.query.registered = queries
	return db.query
}

func newAuthorizer(rows [][]any) (*RoleAuthorizer, *authQueryFake) {
	query := &authQueryFake{rows: rows}
	return &RoleAuthorizer{DB: authDBFake{query: query}}, query
}

// The bind order is generated by keel, so pin it: a swapped subject and tenant
// would authorize a different principal while still returning rows.
func TestAuthorize_AgentBindsSubjectThenTenant(t *testing.T) {
	authorizer, query := newAuthorizer([][]any{{"monthly_revenue", "", false}})

	grant, err := authorizer.Authorize(context.Background(),
		domain.Principal{Kind: domain.PrincipalAgent, ID: "agent-7", TenantID: 42},
		"REPORT", "RUN", "monthly_revenue")
	if err != nil {
		t.Fatalf("authorize: %v", err)
	}
	if !grant.Allowed || grant.BypassScope {
		t.Fatalf("grant = %+v, want an exact value-scoped allow", grant)
	}
	want := []any{"REPORT", "RUN", "agent-7", int64(42), "monthly_revenue"}
	if len(query.args) != len(want) {
		t.Fatalf("args = %v, want %v", query.args, want)
	}
	for i, value := range want {
		if query.args[i] != value {
			t.Fatalf("arg %d = %v, want %v", i, query.args[i], value)
		}
	}
	if sql := query.registered[query.asked]; !strings.Contains(sql, "FROM agent_permission p") {
		t.Errorf("agent grants must come from agent_permission, got:\n%s", sql)
	}
}

func TestAuthorize_HumanUsesKeelUserGrants(t *testing.T) {
	authorizer, query := newAuthorizer([][]any{{"*", "", false}})

	grant, err := authorizer.Authorize(context.Background(),
		domain.Principal{Kind: domain.PrincipalHuman, ID: "11", TenantID: 42},
		"REPORT", "RUN", "monthly_revenue")
	if err != nil {
		t.Fatalf("authorize: %v", err)
	}
	if !grant.Allowed || !grant.BypassScope {
		t.Fatalf("grant = %+v, want a wildcard allow", grant)
	}
	// A human is keel's built-in kind: user id only, no tenant filter.
	want := []any{"REPORT", "RUN", int64(11), "monthly_revenue"}
	if len(query.args) != len(want) {
		t.Fatalf("args = %v, want %v", query.args, want)
	}
	for i, value := range want {
		if query.args[i] != value {
			t.Fatalf("arg %d = %v, want %v", i, query.args[i], value)
		}
	}
	if query.asked != keeldata.DefaultGrantCatalog.CheckQuery(keelmodel.PrincipalUser) {
		t.Errorf("human asked %q, want keel's user grant query", query.asked)
	}
	if sql := query.registered[query.asked]; !strings.Contains(sql, "FROM user_permission p") {
		t.Errorf("human grants must come from user_permission, got:\n%s", sql)
	}
}

func TestAuthorize_ServiceSharesTheAgentGrantTable(t *testing.T) {
	authorizer, query := newAuthorizer(nil)

	if _, err := authorizer.Authorize(context.Background(),
		domain.Principal{Kind: domain.PrincipalService, ID: "svc-1", TenantID: 9},
		"REPORT", "RUN", "x"); err != nil {
		t.Fatalf("authorize: %v", err)
	}
	if sql := query.registered[query.asked]; !strings.Contains(sql, "FROM agent_permission p") {
		t.Errorf("service grants must come from agent_permission, got:\n%s", sql)
	}
}

func TestAuthorize_FailsClosed(t *testing.T) {
	cases := map[string]domain.Principal{
		"zero value":           {},
		"no tenant":            {Kind: domain.PrincipalAgent, ID: "a"},
		"unknown kind":         {Kind: "martian", ID: "a", TenantID: 1},
		"human id not numeric": {Kind: domain.PrincipalHuman, ID: "not-a-user", TenantID: 1},
	}
	for name, principal := range cases {
		authorizer, _ := newAuthorizer([][]any{{"*", "", true}})
		grant, err := authorizer.Authorize(context.Background(), principal, "REPORT", "RUN", "x")
		if err == nil {
			t.Errorf("%s: expected an error", name)
		}
		if grant.Allowed {
			t.Errorf("%s: must not allow", name)
		}
	}
}
